version: "3.7"
services:
  redis-db:
    image: redis:buster
    container_name: redis-buster-0.1
    restart: always
    ports:
      - "6379:6379"
    expose: 
      - "6379"
    environment: 
        REDIS_PASSWORD: "${REDIS_PASS}"